admitme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('', include('education.urls', namespace='education')),
    path('', include('experience.urls', namespace='experiences')),
    path('', include('research.urls', namespace='research')),
    path('', include('skills.urls', namespace='skills')),
    path('', include('interests.urls', namespace='interests')),
    path('', include('contacts.urls', namespace='contacts')),
    
    path('manager/', admin.site.urls),
]

contacts/urls.py
from django.urls import path, include

from .views import contacts
app_name = 'contacts'

urlpatterns = [
    path('contacts', contacts, name='contacts')
   
]

education/urls.py
from django.urls import path, include
from .views import education, education_details

app_name = 'education'

urlpatterns = [

    path('education', education, name='education'),
    # path('education-detail')
     path('education/<slug:slug>/', education_details, name='education_detail'),

   
]

home/urls.py
from django.urls import path, include

from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
   
]

interests/urls.py
from django.urls import path, include

from .views import interests

app_name = 'interests'

urlpatterns = [

    path('interests', interests, name='interests')
   
]

research/urls.py
from django.urls import path, include

from .views import research

app_name = 'research'

urlpatterns = [
    path('research', research, name='research')
   
]

skills/urls.py
from django.urls import path, include
from .views import skills


app_name = 'skills'

urlpatterns = [

   path('skills', skills, name='skills')
]

education/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
def education_image_upload_path(instance, filename):
    return f"education/{filename}"

class Education(models.Model):
    school_name = models.CharField(max_length = 50)
    major = models.CharField(max_length = 50)
    startdate = models.DateField(null=True, default=None)
    enddate = models.DateField(null=True, default=None)
    present = models.BooleanField(default = False)
    about = models.TextField()
    image = models.ImageField(upload_to=education_image_upload_path, blank=True)
    slug = models.SlugField(unique=True, blank=True)  # unique slug and can be blank

    def save(self, *args, **kwargs):
        # Generate slug if it's not provided
        if not self.slug:
            self.slug = slugify(self.school_name)  # Using title to generate slug

        # Call the super method to save the model
        super(Education, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name = "Education"
        verbose_name_plural = "Education"

    def __str__(self):
        return self.school_name

education/views.py
from django.shortcuts import render, get_object_or_404
from education.models import Education
# Create your views here.
def education(request):
    education = Education.objects.all().order_by('-startdate')
    return render(request, 'education/education.html', {'education':education})

def education_details(request, slug):
    detail = get_object_or_404(Education, slug=slug)
    return render(request, 'education/education-detail.html', {'detail':detail})

templates/education/education-detail.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Education</title>
    <link rel="stylesheet" href="skills.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/education-detail.css' %}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:home' %}" target=”_blank” >Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'education:education' %}" target=”_blank” >Education</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'experiences:experiences' %}" target=”_blank” >Experiences</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'research:research' %}" target=”_blank” >Research</a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" href="{% url 'skills:skills' %}" target=”_blank”  >Skills</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'interests:interests' %}" target=”_blank”>Interests</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacts:contacts' %}" target=”_blank”>Contacts</a>
        </li>
      </ul>
   </div>
  </nav>
    <div class="container" id="container">
        <div class="card mb-12">
            <img class="card-img-top" src="{{detail.image.url}}" alt="Card image cap">
            <div class="card-body">
              <h3 class="card-title"><b>{{detail.school_name}}, {{detail.major}}</b></h3>
              <br>
              <p class="card-text">{{detail.about}}</p>
       
            </div>
          </div>
         
    </div>
    <footer class="footer bg-dark navbar-dark">

        <p>Developed by<strong><a href="https://www.linkedin.com/in/farhad-aghayev/">Farhad Aghayev</a></strong>.   &copy; All Rights Reserved</p> 
    
    
    </footer>
</body>
</html>

templates/education/education.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Educational Background</title>
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/education.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:home' %}" target=”_blank” >Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'education:education' %}" target=”_blank” >Education</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'experiences:experiences' %}" target=”_blank” >Experiences</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'research:research' %}" target=”_blank” >Research</a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" href="{% url 'skills:skills' %}" target=”_blank”  >Skills</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'interests:interests' %}" target=”_blank”>Interests</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacts:contacts' %}" target=”_blank”>Contacts</a>
        </li>
      </ul>
   </div>
  </nav>
    <div class="container">

        <h1>My Educational Background</h1>
        <br>
       
        <br>
        <br>
        <div class="educations">
        <div class="row">
          {%for edc in education %}
            <div class="col-sm-4">
                <div class="card" id="card" style="width: 18rem; height: 20rem;">
                    <img class="card-img-top" id="image" src="{{edc.image.url}}" alt="Card image cap">
                    <div class="card-body">
                      <h5 class="card-title">{{edc.school}}</h5>
                      {%if edc.present%}
                      <h6>{{edc.startdate}} - Present</h6>
                      {%else%}
                      <h6>{{edc.startdate}} - {{edc.enddate}}</h6>
                      {%endif%}
                      <p class="card-text">{{edc.major}}</p>
                      <a href="{% url 'education:education_detail' slug=edc.slug %}" class="button">More...</a>
                    </div>
                  </div>
                  
                  </div>
           {%endfor%}
          </div>
    </div>
</div>
<footer class="footer bg-dark navbar-dark">

    <p>Developed by<strong><a href="https://www.linkedin.com/in/farhad-aghayev/">Farhad Aghayev</a></strong>.   &copy; All Rights Reserved</p> 


</footer>
    
</body>
</html>