admitme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('', include('education.urls', namespace='education')),
    path('', include('experience.urls', namespace='experiences')),
    path('', include('research.urls', namespace='research')),
    path('', include('skills.urls', namespace='skills')),
    path('', include('interests.urls', namespace='interests')),
    path('', include('contacts.urls', namespace='contacts')),
    
    path('manager/', admin.site.urls),
]

contacts/urls.py
from django.urls import path, include

from .views import contacts
app_name = 'contacts'

urlpatterns = [
    path('contacts', contacts, name='contacts')
   
]

education/urls.py
from django.urls import path, include
from .views import education, education_details

app_name = 'education'

urlpatterns = [

    path('education', education, name='education'),
    # path('education-detail')
     path('education/<slug:slug>/', education_details, name='education_detail'),

   
]

experience/urls.py
from django.urls import path, include

from .views import experience, experience_detail

app_name = 'experiences'

urlpatterns = [

    path('experience', experience, name='experiences'),
    path('experience/<slug:slug>/', experience_detail, name='experience_detail'),
   
]

home/urls.py
from django.urls import path, include

from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
   
]

research/urls.py
from django.urls import path, include

from .views import research

app_name = 'research'

urlpatterns = [
    path('research', research, name='research')
   
]

skills/urls.py
from django.urls import path, include
from .views import skills


app_name = 'skills'

urlpatterns = [

   path('skills', skills, name='skills')
]

experience/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
def experience_image_upload_path(instance, filename):
    return f"experience/{filename}"

class Experience(models.Model):

    CHOICE_ONE = 'tech'
    CHOICE_TWO = 'mentor'
    CHOICE_THREE = 'social'


    CHOICES = [
        (CHOICE_ONE, 'tech'),
        (CHOICE_TWO, 'mentor'),
        (CHOICE_THREE, 'social'),

    ]

    type = models.CharField(
        max_length=50,
        choices=CHOICES,
        default=CHOICE_ONE,  # You can set a default value if needed
    )
    organization_name = models.CharField(max_length = 50)
    job_title = models.CharField(max_length = 50)
    about = models.TextField()
    startdate = models.DateField(null=True, default=None)
    enddate = models.DateField(null=True, default=None)
    present = models.BooleanField(default = False)
    image = models.ImageField(upload_to=experience_image_upload_path, blank=True)
    slug = models.SlugField(unique=True, blank=True)  # unique slug and can be blank

    def save(self, *args, **kwargs):
        # Generate slug if it's not provided
        if not self.slug:
            self.slug = slugify(self.organization_name)  # Using title to generate slug

        # Call the super method to save the model
        super(Experience, self).save(*args, **kwargs)

    def __str__(self):
        return self.organization_name

experience/views.py
from django.shortcuts import render, get_object_or_404
from experience.models import Experience
# Create your views here.
def experience(request):
    experiences = Experience.objects.all().order_by('-startdate')
    return render(request, 'experience/experiences.html', {'experiences':experiences})


def experience_detail(request, slug):
    detail = get_object_or_404(Experience, slug=slug)
    return render(request, 'experience/experience-detail.html', {'detail':detail})

templates/experience/experience-detail.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Experience</title>
    <link rel="stylesheet" href="skills.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/experience-detail.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:home' %}" target=”_blank” >Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'education:education' %}" target=”_blank” >Education</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'experiences:experiences' %}" target=”_blank” >Experiences</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'research:research' %}" target=”_blank” >Research</a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" href="{% url 'skills:skills' %}" target=”_blank”  >Skills</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'interests:interests' %}" target=”_blank”>Interests</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacts:contacts' %}" target=”_blank”>Contacts</a>
        </li>
      </ul>
   </div>
  </nav>
      <div class="container">
        <div class="card mb-12">
            <img class="card-img-top" src="{{detail.image.url}}" alt="Card image cap">
            <div class="card-body">
              <h3 class="card-title"><b>{{detail.organization_name}}, {{detail.job_title}}</b></h3>
              <br>
              <p class="card-text">{{detail.about}}</p>
       
            </div>
          </div>
         
    </div>
    <footer class="footer bg-dark navbar-dark">

        <p>Developed by<strong><a href="https://www.linkedin.com/in/farhad-aghayev/">Farhad Aghayev</a></strong>.   &copy; All Rights Reserved</p> 
    
    
    </footer>
    
</body>
</html>

templates/experience/experiences.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Experiences</title>
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/experiences.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:home' %}" target=”_blank” >Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'education:education' %}" target=”_blank” >Education</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'experiences:experiences' %}" target=”_blank” >Experiences</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'research:research' %}" target=”_blank” >Research</a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" href="{% url 'skills:skills' %}" target=”_blank”  >Skills</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'interests:interests' %}" target=”_blank”>Interests</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacts:contacts' %}" target=”_blank”>Contacts</a>
        </li>
      </ul>
   </div>
  </nav>
    <div class="container">

        <h1>My Work Experiences</h1>
        <br>
       
        <br>
        <br>
        <div class="experiences">
            <h3>Tech Experiences</h3>
            <br>
            <div class="developer-experiences">
        <div class="row">
          {%for experience in experiences%}
          {% if experience.type == 'tech'%}
                <div class="col-sm-4">
                      <div class="card" id="card" style="width: 22rem; height: 30rem;">
                          <img class="card-img-top" id="image" height="250px" src="{{experience.image.url}}" alt="Card image cap">
                          <div class="card-body">
                            <h5 class="card-title">{{experience.organization_name}}</h5>
                            {%if experience.present%}
                            <h6>{{experience.startdate}} - Present</h6>
                            {%else%}
                            <h6>{{experience.startdate}} - {{experience.enddate}}</h6>
                            {%endif%}
                            <p class="card-text">{{experience.job_title}}</p>
                            <a href="{% url 'experiences:experience_detail' slug=experience.slug %}" class="button">More...</a>
                          </div>
                        </div>
                      
                </div>
                {%endif%}
        {%endfor%}
          </div>
          <br>
        <br>
        </div>

        <br>
        <br>
        <br>
        <br>

        <h3>Mentoring Experiences</h3>
        <br>
        <div class="mentoring-experiences">
          <div class="row">
            {%for experience in experiences%}
            {% if experience.type == 'mentor'%}
                  <div class="col-sm-4">
                        <div class="card" id="card" style="width: 22rem; height: 30rem;">
                            <img class="card-img-top" id="image" height="250px" src="{{experience.image.url}}" alt="Card image cap">
                            <div class="card-body">
                              <h5 class="card-title">{{experience.organization_name}}</h5>
                              {%if experience.present%}
                              <h6>{{experience.startdate}} - Present</h6>
                              {%else%}
                              <h6>{{experience.startdate}} - {{experience.enddate}}</h6>
                              {%endif%}
                              <p class="card-text">{{experience.job_title}}</p>
                              <a href="{% url 'experiences:experience_detail' slug=experience.slug %}" class="button">More...</a>
                            </div>
                          </div>
                        
                  </div>
                  {%endif%}
          {%endfor%}
            </div>
            <br>
        <br>
    </div>
    <br>
    <br>
    <br>
    <br>

    <h3>Social Experiences</h3>
    <br>
    <div class="social-experiences">
      <div class="row">
        {%for experience in experiences%}
        {% if experience.type == 'social'%}
              <div class="col-sm-4">
                    <div class="card" id="card" style="width: 22rem; height: 30rem;">
                        <img class="card-img-top" id="image" height="250px" src="{{experience.image.url}}" alt="Card image cap">
                        <div class="card-body">
                          <h5 class="card-title">{{experience.organization_name}}</h5>
                          {%if experience.present%}
                          <h6>{{experience.startdate}} - Present</h6>
                          {%else%}
                          <h6>{{experience.startdate}} - {{experience.enddate}}</h6>
                          {%endif%}
                          <p class="card-text">{{experience.job_title}}</p>
                          <a href="{% url 'experiences:experience_detail' slug=experience.slug %}" class="button">More...</a>
                        </div>
                      </div>
                    
              </div>
              {%endif%}
      {%endfor%}
        </div>
        <br>
        <br>

</div>
    </div>
</div>
<footer class="footer bg-dark navbar-dark">

    <p>Developed by<strong><a href="https://www.linkedin.com/in/farhad-aghayev/">Farhad Aghayev</a></strong>.   &copy; All Rights Reserved</p> 


</footer>
    
</body>
</html>